// TFLite-backed branch (PRD §10.6, §18.1).
//
// This is the branch that runs a real on-device model. Its most important
// property is what it does when no model is bundled: it reports the branch as
// unavailable and names the reason. It never falls back to a heuristic
// disguised as a model output, and it never returns a default score.
//
// A model only becomes usable when BOTH of these are true:
//   1. assets/models/<model_id>.tflite exists, and
//   2. assets/models/model_manifest.json carries an entry for it with
//      training_status = trained and non-empty metrics.
//
// Requirement 2 is what makes the honesty guarantee structural. The manifest is
// generated by the ml/ pipeline from real evaluation runs, so a .tflite file
// that was never actually evaluated cannot activate a claim in the product.

import 'dart:convert';

import 'package:flutter/foundation.dart' show debugPrint;
import 'package:flutter/services.dart' show AssetBundle, rootBundle;

import '../domain/protocol/models.dart';
import 'branch.dart';
import 'interpreter.dart';

/// One entry in the generated model manifest.
class ModelManifestEntry {
  const ModelManifestEntry({
    required this.modelId,
    required this.version,
    required this.trainingStatus,
    required this.featureKeys,
    required this.dataset,
    required this.metrics,
    required this.outputKind,
    this.placementNote,
    this.limitations = const [],
    this.threshold,
  });

  final String modelId;
  final String version;
  final TrainingStatus trainingStatus;

  /// Feature order the model expects. Inference must feed inputs in exactly
  /// this order — a silent reordering would produce confident nonsense, so the
  /// branch refuses to run when a declared feature is missing rather than
  /// zero-filling the slot.
  final List<String> featureKeys;

  final String dataset;
  final Map<String, dynamic> metrics;

  /// 'risk_score' (0..1) or 'binary'.
  final String outputKind;

  final String? placementNote;
  final List<String> limitations;

  /// Operating point the caller should use, when the training run derived one.
  final double? threshold;

  bool get isUsable =>
      trainingStatus == TrainingStatus.trained && metrics.isNotEmpty && featureKeys.isNotEmpty;

  /// True only when the manifest explicitly says the output was calibrated.
  ///
  /// Deliberately an exact-prefix test rather than a substring search. The
  /// natural value to write for an uncalibrated model is "not_calibrated",
  /// which a `contains('calibrated')` check reads as calibrated — so the
  /// sloppier test would flag the one model that is honestly saying it is NOT
  /// calibrated. That inversion would claim a calibration that never happened,
  /// which is exactly what PRD §26.5 forbids.
  bool get isCalibrated {
    final raw = metrics['calibration'];
    if (raw is! String) return false;
    final value = raw.toLowerCase();
    return value == 'calibrated' || value.startsWith('calibrated');
  }

  static ModelManifestEntry? fromJson(Map<String, dynamic> json) {
    final modelId = json['model_id'];
    final featureKeys = json['feature_keys'];
    if (modelId is! String || featureKeys is! List) return null;
    return ModelManifestEntry(
      modelId: modelId,
      version: json['version'] as String? ?? '0.0.0',
      trainingStatus: TrainingStatus.fromWire(json['training_status'] as String?),
      featureKeys: featureKeys.cast<String>(),
      dataset: json['dataset'] as String? ?? 'unspecified',
      metrics: (json['metrics'] as Map?)?.cast<String, dynamic>() ?? const {},
      outputKind: json['output_kind'] as String? ?? 'risk_score',
      placementNote: json['placement_note'] as String?,
      limitations: (json['limitations'] as List?)?.cast<String>() ?? const [],
      threshold: (json['threshold'] as num?)?.toDouble(),
    );
  }

  /// Human-readable metrics block for the specialist view. Rendered verbatim so
  /// a reviewer sees the real numbers, including the unflattering ones.
  String get metricsSummary {
    if (metrics.isEmpty) return 'No evaluation metrics recorded.';
    final parts = metrics.entries
        .where((e) => e.value is num || e.value is String)
        .map((e) => '${e.key}: ${e.value}')
        .toList(growable: false);
    return parts.join(', ');
  }
}

/// Reads assets/models/model_manifest.json.
class ModelManifest {
  const ModelManifest(this.entries, {this.generatedAt, this.provenance});

  final Map<String, ModelManifestEntry> entries;
  final String? generatedAt;
  final String? provenance;

  static const String assetPath = 'assets/models/model_manifest.json';

  static const ModelManifest empty = ModelManifest({});

  bool get isEmpty => entries.isEmpty;

  ModelManifestEntry? operator [](String modelId) => entries[modelId];

  /// Loads the manifest, returning [empty] when nothing is bundled.
  ///
  /// A missing manifest is the expected state before the first training run, so
  /// it is not an error. A *malformed* manifest is also not fatal: it is treated
  /// as empty, because failing to boot the app over a corrupted optional asset
  /// would block screening entirely, which is worse than losing a model branch.
  static Future<ModelManifest> load({AssetBundle? bundle}) async {
    final assets = bundle ?? rootBundle;
    try {
      final raw = await assets.loadString(assetPath);
      final decoded = jsonDecode(raw) as Map<String, dynamic>;
      final list = decoded['models'] as List? ?? const [];
      final entries = <String, ModelManifestEntry>{};
      for (final item in list) {
        if (item is! Map) continue;
        final entry = ModelManifestEntry.fromJson(item.cast<String, dynamic>());
        if (entry != null) entries[entry.modelId] = entry;
      }
      return ModelManifest(
        entries,
        generatedAt: decoded['generated_at'] as String?,
        provenance: decoded['provenance'] as String?,
      );
    } catch (_) {
      return empty;
    }
  }
}

/// Runs a bundled TFLite model for one branch.
class TfliteBranch implements ScoringBranch {
  TfliteBranch({
    required this.spec,
    required this.manifest,
    AssetBundle? bundle,
  }) : _bundle = bundle ?? rootBundle;

  @override
  final ModelSpec spec;

  final ModelManifest manifest;
  final AssetBundle _bundle;

  TfliteInterpreter? _interpreter;
  bool _loadAttempted = false;

  /// Set when the runtime exists but the artefact itself was missing or
  /// unreadable, so the reason reported is the useful one.
  bool _artefactFailed = false;

  ModelManifestEntry? get _entry => manifest[spec.modelId];

  /// Where the artefact must live if it is bundled.
  String get assetPath => 'assets/models/${spec.modelId}.tflite';

  @override
  Future<bool> get isReady async {
    final entry = _entry;
    if (entry == null || !entry.isUsable) return false;
    await _ensureLoaded();
    return _interpreter != null;
  }

  Future<void> _ensureLoaded() async {
    if (_loadAttempted) return;
    _loadAttempted = true;

    // No point reading the asset on a platform that cannot run it: the branch
    // reports platformUnsupported, which says something different from
    // "the file is missing".
    if (!TfliteInterpreter.isSupported) return;

    try {
      final data = await _bundle.load(assetPath);
      _interpreter = await TfliteInterpreter.load(data.buffer.asUint8List());
      _artefactFailed = _interpreter == null;
    } catch (error) {
      // Log rather than rethrow: a missing or unreadable artefact degrades this
      // branch, it does not fail the screening. Blocking a field screening over
      // an optional asset would be a far worse failure than losing one branch.
      debugPrint(
        'Arogya-NER: TFLite artefact "$assetPath" could not be loaded ($error). '
        'Branch "${spec.modelId}" will report as unavailable.',
      );
      _interpreter = null;
      _artefactFailed = true;
    }
  }

  @override
  Future<BranchScore> score(BranchInput input) async {
    final entry = _entry;
    if (entry == null) {
      return BranchScore.unavailable(
        branch: spec.branch,
        reason: BranchUnavailableReason.untrained,
        modelId: spec.modelId,
        modelVersion: spec.version,
        trainingStatus: spec.trainingStatus,
      );
    }

    // Refuse to run with a partial feature vector. Zero-filling absent features
    // would present an imputed value as a measurement, which is exactly the
    // fabrication PRD §26.5 forbids.
    final missing = entry.featureKeys.where((k) => !input.has(k)).toList(growable: false);
    if (missing.isNotEmpty) {
      return BranchScore.unavailable(
        branch: spec.branch,
        reason: BranchUnavailableReason.missingInput,
        modelId: spec.modelId,
        modelVersion: entry.version,
        trainingStatus: entry.trainingStatus,
      );
    }

    await _ensureLoaded();
    final interpreter = _interpreter;
    if (interpreter == null) {
      return BranchScore.unavailable(
        branch: spec.branch,
        reason: TfliteInterpreter.isSupported
            ? (_artefactFailed
                ? BranchUnavailableReason.artefactUnavailable
                : BranchUnavailableReason.notImplemented)
            : BranchUnavailableReason.platformUnsupported,
        modelId: spec.modelId,
        modelVersion: entry.version,
        trainingStatus: entry.trainingStatus,
      );
    }

    final vector = entry.featureKeys
        .map((k) => input[k] ?? 0)
        .toList(growable: false);

    final double raw;
    try {
      raw = interpreter.run(vector);
    } catch (error) {
      debugPrint('Arogya-NER: inference failed for "${spec.modelId}": $error');
      return BranchScore.unavailable(
        branch: spec.branch,
        reason: BranchUnavailableReason.notImplemented,
        modelId: spec.modelId,
        modelVersion: entry.version,
        trainingStatus: entry.trainingStatus,
      );
    }

    // Modality confidence comes from the quality gate, not from the model, so a
    // good model fed a bad capture still reports honestly.
    final modality = switch (spec.branch) {
      ModelBranch.imuTemporal || ModelBranch.stage1Localisation => 'wearable',
      ModelBranch.cameraTemporal => 'camera',
      ModelBranch.clinicalTabular => 'questionnaire',
      _ => 'camera',
    };

    return BranchScore(
      branch: spec.branch,
      score: raw.clamp(0.0, 1.0).toDouble(),
      confidence: input.confidenceFor(modality),
      trainingStatus: entry.trainingStatus,
      modelId: spec.modelId,
      modelVersion: entry.version,
      // A tree ensemble exported to TFLite has no dense gradient to attribute,
      // so contributions stay empty rather than being invented. The manifest's
      // metrics and the branch's limitations carry the explanation instead.
      contributions: const [],
      limitations: [
        ...entry.limitations,
        if (!entry.isCalibrated) 'Model output has not been calibrated on a '
            'held-out population; treat the score as a ranking, not a probability.',
      ],
      placementNote: entry.placementNote,
      attributionMethod: 'none',
    );
  }

  /// Releases the interpreter. Called when a screening session ends, because an
  /// interpreter holds native memory that would otherwise accumulate across
  /// patients on a memory-constrained device.
  void dispose() {
    _interpreter?.close();
    _interpreter = null;
    _loadAttempted = false;
    _artefactFailed = false;
  }
}
