// Train/serve parity test.
//
// The fixture is generated by ml/common/parity.py, which holds the canonical
// definitions. This test runs the Dart mirror over the identical inputs and
// asserts the outputs match.
//
// This is the single most important test in the wearable pipeline. If it fails,
// every trained model in the app is being fed numbers it did not learn on, and
// the failure would otherwise be completely invisible — the model would still
// return a confident score.

import 'dart:convert';
import 'dart:io';

import 'package:arogya_ner/wearable/imu_features.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;

void main() {
  final fixtureFile = File(p.join('test', 'fixtures', 'imu_feature_parity.json'));

  test('the parity fixture exists (run: python ml/common/parity.py)', () {
    expect(
      fixtureFile.existsSync(),
      isTrue,
      reason: 'generate it with "python ml/common/parity.py" from the repo root',
    );
  });

  late Map<String, dynamic> fixture;
  late double tolerance;

  setUpAll(() {
    fixture = jsonDecode(fixtureFile.readAsStringSync()) as Map<String, dynamic>;
    tolerance = (fixture['tolerance'] as num).toDouble();
  });

  test('the feature order matches the documented contract', () {
    final fixtureOrder = (fixture['feature_order'] as List).cast<String>();
    expect(
      imuFeatureOrder,
      fixtureOrder,
      reason: 'the order models are trained and served in must not drift',
    );
  });

  List<List<double>>? samples(dynamic raw) {
    if (raw == null) return null;
    return (raw as List)
        .map((row) => (row as List).map((v) => (v as num).toDouble()).toList())
        .toList(growable: false);
  }

  test('every fixture case reproduces the Python features exactly', () {
    final cases = (fixture['cases'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);

    final failures = <String>[];

    for (final testCase in cases) {
      final name = testCase['name'] as String;
      final trial = ImuTrial(
        sampleRateHz: (testCase['sample_rate_hz'] as num).toDouble(),
        proximal: samples(testCase['proximal']),
        distal: samples(testCase['distal']),
      );

      final actual = extractImuFeatures(trial);
      final expected = (testCase['expected'] as Map).cast<String, dynamic>();
      final expectedAbsent = (testCase['expected_absent'] as List).cast<String>();

      for (final entry in expected.entries) {
        final want = (entry.value as num).toDouble();
        final got = actual[entry.key];

        if (got == null) {
          failures.add('$name: ${entry.key} missing (Python produced $want)');
          continue;
        }
        if ((got - want).abs() > tolerance) {
          failures.add(
            '$name: ${entry.key} drift — Python $want vs Dart $got '
            '(delta ${(got - want).abs()})',
          );
        }
      }

      for (final key in expectedAbsent) {
        if (actual.containsKey(key)) {
          failures.add(
            '$name: $key should be ABSENT (single pod) but Dart produced '
            '${actual[key]}',
          );
        }
      }

      // The Dart side must not invent features the canonical implementation
      // did not compute either.
      for (final key in actual.keys) {
        if (!expected.containsKey(key) && !expectedAbsent.contains(key)) {
          failures.add('$name: Dart produced unexpected feature "$key"');
        }
      }
    }

    expect(
      failures,
      isEmpty,
      reason: 'IMU feature extraction has diverged between training and '
          'on-device inference:\n${failures.join('\n')}',
    );
  });

  group('edge cases the parity fixture pins down', () {
    test('a motionless trace yields exactly zero for variability features', () {
      final testCase = (fixture['cases'] as List)
          .cast<Map<String, dynamic>>()
          .firstWhere((c) => c['name'] == 'static_zero_variance');

      final trial = ImuTrial(
        sampleRateHz: (testCase['sample_rate_hz'] as num).toDouble(),
        proximal: samples(testCase['proximal']),
        distal: samples(testCase['distal']),
      );
      final features = extractImuFeatures(trial);

      expect(features['imu_acc_magnitude_std'], 0);
      expect(features['imu_acc_jerk_mean'], 0);
      expect(features['imu_gyro_hf_variance'], 0);
      expect(features['imu_acc_magnitude_mean'], closeTo(1.0, 1e-9));
    });

    test('a trace with dropouts reports signal quality below 1', () {
      final testCase = (fixture['cases'] as List)
          .cast<Map<String, dynamic>>()
          .firstWhere((c) => c['name'] == 'with_dropouts_and_saturation');

      final trial = ImuTrial(
        sampleRateHz: (testCase['sample_rate_hz'] as num).toDouble(),
        proximal: samples(testCase['proximal']),
      );
      final quality = extractImuFeatures(trial)['imu_signal_quality']!;

      expect(quality, lessThan(1.0));
      expect(quality, greaterThan(0.5));
    });

    test('a two-sample trace degrades to zeros rather than NaN', () {
      final testCase = (fixture['cases'] as List)
          .cast<Map<String, dynamic>>()
          .firstWhere((c) => c['name'] == 'too_short');

      final trial = ImuTrial(
        sampleRateHz: (testCase['sample_rate_hz'] as num).toDouble(),
        proximal: samples(testCase['proximal']),
      );
      final features = extractImuFeatures(trial);

      for (final value in features.values) {
        expect(value.isFinite, isTrue,
            reason: 'a NaN here would silently poison a model input');
      }
    });

    test('a single-pod trial omits relative-motion features rather than zeroing them', () {
      final testCase = (fixture['cases'] as List)
          .cast<Map<String, dynamic>>()
          .firstWhere((c) => c['name'] == 'single_pod');

      final trial = ImuTrial(
        sampleRateHz: (testCase['sample_rate_hz'] as num).toDouble(),
        proximal: samples(testCase['proximal']),
      );
      final features = extractImuFeatures(trial);

      expect(features.containsKey('imu_proximal_distal_correlation'), isFalse);
      expect(features.containsKey('imu_relative_phase_lag'), isFalse);

      // Asking for a full vector must therefore fail loudly, not fabricate.
      expect(
        () => imuFeatureVector(trial),
        throwsA(isA<StateError>()),
      );
    });
  });

  test('malformed input is rejected rather than coerced', () {
    expect(
      () => extractImuFeatures(const ImuTrial(
        sampleRateHz: 50,
        proximal: [
          [0, 0, 1],
        ],
      )),
      throwsA(isA<ArgumentError>()),
    );

    expect(
      () => extractImuFeatures(const ImuTrial(sampleRateHz: 50)),
      throwsA(isA<ArgumentError>()),
    );
  });

  test('research-grade signals are declared so they can be excluded', () {
    expect(researchGradeImuFeatures, contains('imu_gyro_hf_variance'));
    expect(researchGradeImuFeatures, contains('imu_relative_phase_lag'));
    expect(researchGradeImuFeatures, isNot(contains('imu_acc_magnitude_mean')));
  });
}
